### ISSUE TITLE
Many Bulk Wallet Addresses won't verify via Wallet Details

### ISSUE THREAD

**Issue by SJ02** [bitcoinz-sites/paper.btcz.rocks#9]
Working offline with paper.btcz.rocks this morning I generated a Bulk Wallet of 20 addresses. Then I copy/pasted each PK into the Wallet Details tab to see if it would back-generate the address correctly. About half did, and about half didn't. The successes output the addresses and QR codes as expected. The failures simply did nothing. 

I inquired on Dischordapp.com and another user did a similar test.  He reports:

Hmm, there seems to be an error in the console: Uncaught RangeError: private key length is invalid

For me this was all on a deep cold machine and so I don't have further info available at the moment, but since the user on Dischordapp.com was able to see the problem as well, I imagine you will be able to also.

**Comment by cryptorex** [comment]
hi thanks for letting us know - we've addressed this with upstream fix and a PR is awaiting merge https://github.com/bitcoinz-sites/paper.btcz.rocks/pull/10
